spring:
  profiles:
    active: local
  datasource:
    username: root
    password: test1234
    #DriverSpy를 통해 log4j로 db 로그 수집
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/demo_project
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 20
      minimum-idle: 2
      connection-test-query: SELECT 1
  # Redis(cache storage)를 통해 캐싱 정보를 빠르게 조회 -> 회원 정보 등
  redis:
    host: 127.0.0.1
    port: 6379
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
    suffix: .html
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
server:
  port: 8000
  servlet:
    session:
      cookie:
        path: /
        http-only: true
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.demoproject.domain